name: sparrow-extensions
channels:
  - conda-forge
dependencies:
  # Build dependencies
  - cmake
  - ninja
  - cxx-compiler
  # Libraries dependencies
  - nlohmann_json
  - sparrow-devel
  # Testing dependencies
  - doctest
  # Documentation dependencies
  - doxygen
  - graphviz
